name: flutterstudy
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
    sdk: ">=2.1.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ">=0.1.2 <2.0.0"
    english_words: ">=3.1.0 <5.0.0"
    fluttertoast: ">=3.1.3 <9.0.0"
    dio: ">=3.0.3 <6.0.0"
    cached_network_image: ">=1.1.1 <4.0.0"
    pull_to_refresh: ">=1.5.6 <3.0.0"
    flutter_spinkit: ">=4.0.0 <6.0.0"
    provider: ">=3.1.0 <7.0.0"
    qr_utils: ^0.1.4
    flutter_redux: ">=0.5.3 <0.11.0"
    flare_flutter: ">=1.5.12 <4.0.0"
    # fluro: ^1.3.4
    # event_bus: ^1.0.1
    # image_picker: ^0.5.0
    # sqflite: ^1.1.5
    # url_launcher: ^5.0.2
    # 本地存储、收藏功能
    # shared_preferences: ^0.4.3
    # share: ^0.6.1+1
    # flutter_webview_plugin: ^0.3.5
    # cookie_jar: ^1.0.0
    # 日期格式化
    # intl: 0.15.7
    # city_pickers: ^0.0.1
    # firebase_analytics: ^1.1.0
    #firebase_auth: ^0.8.3 #auth
    # firebase_core: ^0.3.4 # add dependency for Firebase Core
    # flutter_bloc: ^0.11.1
    # bloc: ^0.12.0
    # html: ^0.14.0+2
    # markdown: ^2.0.0
    # meta: ^1.0.5
    # string_scanner: ^1.0.0
    # path: ^1.5.1
    # flutter_downloader: ^1.1.7
    # path_provider: ^1.1.0
    # permission_handler: ^3.0.0
    # open_file: ^2.0.1+2
    # package_info: ^0.4.0+3
    # flutter_jpush: ^0.0.4
    # zefyr:
    #   path: ./zefyr
dev_dependencies:
    flutter_test:
        sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true
    assets:
        - static/images/
    # To add assets to your application, add an assets section, like this:
    # assets:
    #  - images/a_dot_burr.jpeg
    #  - images/a_dot_ham.jpeg
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
    # assets:
    #     - assets/images/logo.png
    #     - assets/images/welcome.png
    #     - assets/images/default_img.png
    #     - assets/files/flare_flutter_logo_.flr
